### PR TITLE
Add support to use specific omnisharp version

### PR DESCRIPTION
**Pull request by eruizc-dev**
### About

This PR allows to configure which omnisharp version to use. Defaults to latest.

### Considerations

 - Does not notify if version is incorrect
 - I couldn't manage for it to upgrade/downgrade without manual deletion of existing package.

### CODE REVIEW

**Review by yatli — APPROVED** [review]
Nice. And thanks for documenting the knobs!

**Comment by edugomez102** [comment]
I've noticed an error on the README.md since I was unable to download the server.
Change `"omnisharp.version": "v.1.37.3",` to `"omnisharp.version": "v1.37.3",` since there's no dot in the release tag.

**Comment by eruizc-dev** [comment]
> I've noticed an error on the README.md since I was unable to download the server.
> Change `"omnisharp.version": "v.1.37.3",` to `"omnisharp.version": "v1.37.3",` since there's no dot in the release tag.

Oops, can you @yatli directly fix this or do I PR?

**Comment by yatli** [comment]
I got this.

**Pull request merged**
